# Generated by Django 4.0.5 on 2023-03-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeModule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='regExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
