# Generated by Django 4.0.5 on 2023-03-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeModule', '0003_category_alter_prodcat_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodcat',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
