# Generated by Django 4.0.5 on 2023-03-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeModule', '0007_alter_prodcat_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Ordered', 'ORDERED'), ('Shipped', 'SHIPPED'), ('Delivered', 'DELIVERED')], default='Ordered', max_length=10)),
            ],
        ),
    ]
