# Generated by Django 4.0.5 on 2023-03-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeModule', '0010_payment_delete_paymemnt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AddField(
            model_name='track',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='track',
            name='orderDesc',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='track',
            name='orderPrice',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='track',
            name='orderTitle',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
