# Generated by Django 4.0.5 on 2023-03-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeModule', '0012_track_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='deliverystatus',
            field=models.CharField(choices=[('Successful', 'Successful'), ('Unsuccessful', 'Unsuccessful')], default='Successful', max_length=50),
        ),
    ]
